<script setup lang="ts">
const route = useRoute()
const { tutorials } = useContent()
const { data: list } = await useAsyncData('tutorial-detail', tutorials)
const tutorial = computed(() => list.value?.find(item => item.slug === route.params.slug))
if (!tutorial.value) throw createError({ statusCode: 404, statusMessage: '没有找到这份教程' })
useSeoMeta({ title: () => tutorial.value?.title || '手作教程', description: () => tutorial.value?.summary })
useHead({ script: [{ type: 'application/ld+json', innerHTML: computed(() => JSON.stringify({ '@context': 'https://schema.org', '@type': 'HowTo', name: tutorial.value?.title, description: tutorial.value?.summary, step: tutorial.value?.steps.map(step => ({ '@type': 'HowToStep', name: step.title, text: step.description })) })) }] })
</script>
<template><div v-if="tutorial"><section class="bg-ink py-16 text-flour md:py-24"><div class="page-wrap"><NuxtLink to="/diy" class="text-sm font-semibold text-[#ff9b78]">← 返回手作体验</NuxtLink><div class="mt-8 grid items-end gap-10 md:grid-cols-2"><div><p class="eyebrow">{{ tutorial.type }}</p><h1 class="display-title mt-5">{{ tutorial.title }}</h1><p class="mt-7 text-lg leading-8 text-flour/65">{{ tutorial.summary }}</p><div class="mt-8 flex flex-wrap gap-3"><span class="rounded-full border border-white/15 px-4 py-2 text-sm">{{ tutorial.duration }}</span><span class="rounded-full border border-white/15 px-4 py-2 text-sm">{{ tutorial.people }}</span></div></div><div class="aspect-[4/3] overflow-hidden rounded-[2rem]"><img :src="tutorial.image" :alt="tutorial.imageAlt" class="image-cover"></div></div></div></section><section class="page-wrap grid gap-12 py-16 md:grid-cols-[0.7fr_1.3fr] md:py-24"><aside><p class="eyebrow">准备内容</p><ul class="mt-5 grid gap-3 text-charcoal"><li v-for="item in tutorial.materials" :key="item" class="flex gap-3"><span class="text-fire">●</span>{{ item }}</li></ul></aside><div><p class="eyebrow">体验流程</p><ol class="mt-6 grid gap-5"><li v-for="(step, index) in tutorial.steps" :key="step.title" class="paper-card grid gap-4 p-6 md:grid-cols-[4rem_1fr] md:p-8"><span class="font-serif text-4xl text-fire">0{{ index + 1 }}</span><div><h2 class="font-serif text-2xl font-semibold">{{ step.title }}</h2><p class="mt-3 leading-7 text-charcoal">{{ step.description }}</p></div></li></ol><div class="mt-10 rounded-[1.5rem] bg-[#eadbc8] p-7"><h2 class="font-serif text-2xl font-semibold">体验前请留意</h2><ul class="mt-4 grid gap-2 text-charcoal"><li v-for="note in tutorial.notes" :key="note">· {{ note }}</li></ul></div></div></section><ContactPanel /></div></template>

