<script setup lang="ts">
const { settings } = useContent()
const { data: site } = await useAsyncData('visit-settings', settings)
const config = useRuntimeConfig()
const phone = computed(() => String(config.public.phone || site.value?.phone || ''))
const wechat = computed(() => String(config.public.wechat || site.value?.wechat || ''))
const amap = computed(() => String(config.public.amapUrl || site.value?.amapUrl || ''))
const faqs = [{ q: 'DIY需要提前联系吗？', a: '建议提前通过微信或电话确认日期、人数和当天接待能力。具体提前时间待店主确认。' }, { q: '节假日需要排队吗？', a: '窑烤产品按炉次出炉，节假日可能需要等待，请留意首页临时公告。' }, { q: '可以带儿童或宠物吗？', a: '相关规则待店主确认。儿童靠近窑炉操作区时必须由监护人陪同。' }]
useSeoMeta({ title: '到店指南', description: '查看李老汉窑烤面包的地址、营业时间、停车提示、地图导航与咨询方式。' })
</script>
<template><div><PageHero eyebrow="PLAN YOUR VISIT" title="进村、找火、等出炉。" description="出发前请查看营业公告和当天供应。完整门牌、营业时间、停车路线与联系方式需要店主确认后在后台发布。"><div class="flex flex-wrap gap-3"><a v-if="amap" :href="amap" class="btn-primary" target="_blank" rel="noopener">高德地图导航</a><span v-else class="btn-primary cursor-not-allowed opacity-70">导航链接待确认</span><a v-if="phone" :href="`tel:${phone}`" class="btn-secondary">拨打电话</a></div></PageHero><section class="page-wrap grid gap-8 py-16 md:grid-cols-2 md:py-24"><article class="paper-card p-7 md:p-10"><p class="eyebrow">地址与营业</p><h2 class="mt-4 font-serif text-3xl font-semibold">李老汉窑烤面包</h2><dl class="mt-7 grid gap-6"><div><dt class="text-sm font-semibold">地址</dt><dd class="mt-2 leading-7 text-charcoal">{{ site?.address }}</dd></div><div><dt class="text-sm font-semibold">营业时间</dt><dd class="mt-2 leading-7 text-charcoal">{{ site?.hours }}</dd></div><div><dt class="text-sm font-semibold">停车与进村</dt><dd class="mt-2 leading-7 text-charcoal">{{ site?.parking }}</dd></div><div><dt class="text-sm font-semibold">当前公告</dt><dd class="mt-2 leading-7 text-fire">{{ site?.notice }}</dd></div></dl></article><article id="contact" class="paper-card p-7 md:p-10"><p class="eyebrow">联系门店</p><h2 class="mt-4 font-serif text-3xl font-semibold">咨询DIY或当天供应</h2><div class="mt-7 grid gap-4"><div class="rounded-2xl bg-ink/5 p-5"><p class="text-sm font-semibold">电话</p><a v-if="phone" :href="`tel:${phone}`" class="mt-2 block text-xl text-fire">{{ phone }}</a><p v-else class="mt-2 text-charcoal">待店主提供公开咨询电话</p></div><div id="wechat" class="rounded-2xl bg-ink/5 p-5"><p class="text-sm font-semibold">微信</p><p v-if="wechat" class="mt-2 text-xl text-fire">{{ wechat }}</p><p v-else class="mt-2 text-charcoal">待店主提供微信号与二维码</p><img v-if="site?.wechatQr" :src="site.wechatQr" :alt="site.wechatQrAlt" class="mt-4 aspect-square w-40 rounded-xl bg-white object-contain p-2"><div v-else class="mt-4 grid aspect-square w-40 place-items-center rounded-xl border border-dashed border-ink/25 bg-white text-center text-xs leading-5 text-charcoal">微信二维码<br>后台上传后显示</div></div></div></article></section><section class="bg-[#eadbc8] py-16 md:py-20"><div class="page-wrap"><p class="eyebrow">BEFORE YOU COME</p><h2 class="section-title mt-4">到店前常见问题</h2><div class="mt-10 grid gap-4 md:grid-cols-3"><article v-for="item in faqs" :key="item.q" class="rounded-[1.5rem] bg-flour p-7"><h3 class="font-serif text-xl font-semibold">{{ item.q }}</h3><p class="mt-4 leading-7 text-charcoal">{{ item.a }}</p></article></div></div></section></div></template>
