import type { StrapiApp } from '@strapi/strapi/admin';

const zhHansTranslations: Record<string, string> = {
  'app.components.LeftMenu.navbrand.title': '李老汉内容后台',
  'HomePage.header.title': '你好，{name}',
  'HomePage.header.subtitle': '管理门店产品、手作教程、打卡指南和营业信息。',
  'HomePage.widget.loading': '正在加载',
  'HomePage.widget.error': '内容加载失败',
  'HomePage.widget.no-data': '暂无数据',
  'HomePage.widget.no-permissions': '你没有查看此内容的权限',
  'app.components.Select.placeholder': '请选择',
  'app.utils.refresh': '刷新',
  'app.utils.published': '已发布',
  'app.utils.ready-to-publish': '可以发布',
  'app.utils.already-published': '已经发布',
  'app.utils.ready-to-publish-changes': '有修改待发布',
  'app.utils.ready-to-unpublish-changes': '可以取消发布',
  'app.confirm.body': '确定要执行此操作吗？',
  'components.ViewSettings.tooltip': '设置列表显示',
  'global.home': '首页',
  'global.more': '更多',
  'global.new': '新建',
  'global.profile.settings': '个人设置',
  'global.fullname': '姓名',
  'global.last-change.redo': '重做',
  'global.last-change.undo': '撤销',
  'global.last-changes.discard': '放弃修改',
  'content-manager.actions.clone.label': '复制',
  'content-manager.actions.delete.label': '删除',
  'content-manager.actions.discard.label': '放弃修改',
  'content-manager.actions.edit.label': '编辑',
  'content-manager.actions.open-in-new-tab.label': '在新标签页打开',
  'content-manager.actions.copy-documentId.label': '复制内容编号',
  'content-manager.actions.copy-documentId.success': '内容编号已复制',
  'content-manager.actions.unpublish.dialog.body': '取消发布后，访客将无法在官网看到此内容。',
  'content-manager.actions.unpublish.dialog.option.keep-draft': '保留当前草稿',
  'content-manager.actions.unpublish.dialog.option.replace-draft': '用已发布内容替换草稿',
  'content-manager.HeaderLayout.button.label-add-entry': '新建内容',
  'content-manager.components.AddFilterCTA.add': '添加筛选条件',
  'content-manager.components.AddFilterCTA.hide': '隐藏筛选条件',
  'content-manager.components.FilterOptions.button.apply': '应用',
  'content-manager.components.FiltersPickWrapper.PluginHeader.actions.clearAll': '清除全部',
  'content-manager.components.LeftMenu.Search.label': '搜索内容类型',
  'content-manager.components.LeftMenu.collection-types': '内容列表',
  'content-manager.components.LeftMenu.single-types': '单页内容',
  'content-manager.components.LimitSelect.itemsPerPage': '每页条数',
  'content-manager.components.Select.draft-info-title': '草稿版本',
  'content-manager.components.Select.publish-info-title': '已发布版本',
  'content-manager.components.uid.apply': '应用',
  'content-manager.components.uid.available': '可使用',
  'content-manager.components.uid.regenerate': '重新生成',
  'content-manager.components.uid.suggested': '建议值',
  'content-manager.components.uid.unavailable': '已被占用',
  'content-manager.containers.edit.tabs.draft': '草稿',
  'content-manager.containers.edit.tabs.published': '已发布',
  'content-manager.containers.edit.panels.default.title': '内容',
  'content-manager.containers.edit.panels.default.more-actions': '更多操作',
  'content-manager.containers.edit.title.new': '新建内容',
  'content-manager.containers.edit.information.last-published.label': '最后发布时间',
  'content-manager.containers.edit.information.last-draft.label': '最后保存时间',
  'content-manager.containers.edit.information.documentId.label': '内容编号',
  'content-manager.containers.EditView.publishHint': '发布后，官网访客可以看到此内容。',
  'content-manager.containers.EditView.saveHint': '保存为草稿，不会立即显示在官网。',
  'content-manager.containers.List.draft': '草稿',
  'content-manager.containers.List.published': '已发布',
  'content-manager.containers.List.modified': '已修改',
  'content-manager.containers.List.statusFilter.draft': '草稿',
  'content-manager.containers.List.statusFilter.published': '已发布',
  'content-manager.containers.List.statusFilter.publishedModified': '已发布且有修改',
  'content-manager.containers.List.statusFilter.publishedUnmodified': '已发布且无修改',
  'content-manager.validation.error': '内容中有未填写或格式不正确的字段，请根据红色提示修正后再保存或发布。',
  'content-manager.validation.error.unreadable-required-field': '当前账号无权查看部分必填字段，请联系管理员调整权限。',
  'upload.assets.uploaded': '已成功上传 {number} 个文件',
  'upload.asset-details.title': '文件详情',
  'upload.asset-details.description': '查看和修改图片或文件信息',
  'upload.asset-details.fileInfo': '文件信息',
  'upload.asset-details.size': '文件大小',
  'upload.asset-details.dimensions': '图片尺寸',
  'upload.asset-details.creationDate': '上传时间',
  'upload.asset-details.lastUpdated': '最后修改',
  'upload.asset-details.createdBy': '上传人',
  'upload.asset-details.extension': '文件格式',
  'upload.asset-details.fileName': '文件名',
  'upload.asset-details.caption': '图片说明',
  'upload.asset-details.alternativeText': '替代文字',
  'upload.asset-details.location': '所在文件夹',
  'upload.asset-details.save': '保存修改',
  'upload.asset-details.update.success': '文件已更新',
  'upload.asset-details.location.root': '媒体库',
  'upload.asset-details.delete.trigger': '删除文件',
  'upload.asset-details.delete.title': '确定删除这个文件吗？',
  'upload.asset-details.delete.description': '删除后无法恢复；如果内容正在使用此文件，对应位置将无法正常显示。',
  'upload.asset-details.replace.trigger': '替换文件',
  'upload.asset-details.replace.title': '替换当前文件',
  'upload.asset-details.copy-link.trigger': '复制文件链接',
  'upload.asset-details.copy-link.success': '文件链接已复制',
  'upload.asset-details.download.trigger': '下载文件',
  'upload.upload.progress': '上传进度',
  'upload.upload.progress.failed': '上传失败',
  'upload.upload.progress.success': '上传完成',
  'upload.upload.progress.cancel': '取消上传',
  'upload.upload.progress.retry': '重新上传',
  'upload.dropzone.upload.message': '拖放文件到这里，或点击选择文件',
  'upload.folder.create.title': '新建文件夹',
  'upload.folder.form.name.label': '文件夹名称',
  'upload.folder.create.submit': '创建',
  'upload.folder.rename.title': '重命名文件夹',
  'upload.folder.rename.submit': '保存',
  'upload.header.search.placeholder': '搜索图片和文件',
  'upload.import-files': '上传文件',
  'upload.import-from-url': '从网址导入',
  'upload.list.empty.title': '媒体库暂无文件',
  'upload.list.empty.description': '上传门店、产品、DIY 或镇山村实拍图片。',
  'upload.list.empty.add-assets': '上传文件',
  'upload.list.filters.trigger': '筛选',
  'upload.list.filters.clear': '清除筛选',
  'upload.list.sort.trigger': '排序',
  'upload.list.sort.oldest-uploads': '最早上传',
  'upload.list.sort.most-recent-updates': '最近修改',
  'upload.list.sort.name-asc': '名称正序',
  'upload.list.sort.name-desc': '名称倒序',
  'upload.list.assets.actions.replace': '替换',
  'upload.list.assets.actions.copy-link': '复制链接',
  'upload.list.assets.actions.download': '下载',
  'upload.list.assets.actions.move': '移动',
  'upload.list.assets.actions.delete': '删除',
  'upload.plugin.home': '媒体库',
  'upload.sidebar.title': '文件夹',
  'upload.sidebar.home': '全部文件',
  'upload.sidebar.folders': '文件夹',
  'upload.view.grid': '网格视图',
  'upload.view.table': '列表视图',
};

export default {
  config: {
    locales: ['zh-Hans'],
    notifications: { releases: false },
    tutorials: false,
    translations: {
      'zh-Hans': zhHansTranslations,
    },
  },
  bootstrap(_app: StrapiApp) {
    const currentLanguage = window.localStorage.getItem('strapi-admin-language');
    if (!currentLanguage || currentLanguage === 'en') {
      window.localStorage.setItem('strapi-admin-language', 'zh-Hans');
      document.documentElement.setAttribute('lang', 'zh-Hans');
    }
  },
};
